server:
  port: 9292

spring:
  application:
    name: SyncBook
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      stop:
        command: stop
        timeout: 10
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql:5431//localhost/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

logging:
  level:
    root: WARN
    com.example.sync_book: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG


minio.root.user: ${MINIO_ROOT_USER}
minio.root.password: ${MINIO_ROOT_PASSWORD}
minio.endpoint: ${MINIO_ENDPOINT}
minio.bucket.name: ${MINIO_BUCKET_NAME}

application.version: 1.0.0
application.description: SyncBook is a microservice designed to store and synchronize audio and text files