server:
  port: 9292

spring:
  application:
    name: SyncBook
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:postgresql:5431//localhost/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


minio.root.user: ${MINIO_ROOT_USER}
minio.root.password: ${MINIO_ROOT_PASSWORD}
minio.endpoint: ${MINIO_ENDPOINT}
minio.bucket.name: ${MINIO_BUCKET_NAME}